<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)'=='d3d8to9'">
    <OutDir>$(SolutionDir)bin\$(Configuration)\</OutDir>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.local.targets" Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.targets')" />
</Project>
